name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
            compiler: dmd-latest
          - os: ubuntu-latest 
            arch: amd64
            compiler: ldc-master
          - os: ubuntu-24.04-arm 
            arch: arm64
            compiler: ldc-master
          - os: macos-latest
            arch: arm64
            compiler: dmd-latest
          - os: macos-latest
            arch: arm64
            compiler: ldc-master
          - os: windows-latest
            arch: amd64
            compiler: dmd-latest
          - os: windows-latest
            arch: amd64
            compiler: ldc-master
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: dlang-community/setup-dlang@v2
        with:
          compiler: ${{matrix.compiler}}
      - name: Build
        run: dub build
      - name: Bench
        if: runner.os != 'Windows'
        run: dub -q | dd bs=8k count=819200 of=/dev/null
